%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-rqt-reconfigure
Version:        0.5.1
Release:        1%{?dist}
Summary:        ROS rqt_reconfigure package

License:        BSD
URL:            http://wiki.ros.org/rqt_reconfigure
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       PyYAML
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-python-qt-binding >= 0.2.19
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rqt-console
Requires:       ros-melodic-rqt-gui
Requires:       ros-melodic-rqt-gui-py
Requires:       ros-melodic-rqt-py-common
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest

%description
This rqt plugin succeeds former dynamic_reconfigure's GUI (reconfigure_gui), and
provides the way to view and edit the parameters that are accessible via
dynamic_reconfigure. (12/27/2012) In the future, arbitrary parameters that are
not associated with any nodes (which are not handled by dynamic_reconfigure)
might become handled. However, currently as the name indicates, this pkg solely
is dependent on dynamic_reconfigure that allows access to only those params
latched to nodes.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Fri Oct 25 2019 Scott K Logan <logans@cottsay.net> - 0.5.1-1
- Autogenerated by Bloom

* Tue Oct 22 2019 Scott K Logan <logans@cottsay.net> - 0.5.0-1
- Autogenerated by Bloom

* Thu Apr 19 2018 Scott K Logan <logans@cottsay.net> - 0.4.10-0
- Autogenerated by Bloom

